# Generated by Django 3.2.21 on 2023-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('artist_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
