# Generated by Django 3.2.21 on 2023-10-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('products', '0003_auto_20230927_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_finish',
        ),
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist'),
        ),
    ]
